const projectIdeas = [
    "Build a personal portfolio website",
    "Create a weather application",
    "Develop a recipe finder",
    "Make a to-do list app",
    "Design a blog platform",
    "Build an e-commerce website",
    "Create a social media dashboard",
    "Develop a travel booking website",
    "Make a fitness tracker app",
    "Design an expense tracker",
    "Create a job board website",
    "Build a photo gallery website",
    "Develop a movie recommendation system",
    "Make a language learning app",
    "Design a music streaming app",
    "Create a book review website",
    "Build a task management system",
    "Develop a personal finance app",
    "Make a quiz application",
    "Design a news aggregator",
    "Create a virtual event platform",
    "Build a real estate listing site",
    "Develop a ride-sharing app",
    "Make a crowdfunding platform",
    "Design a podcast aggregator",
    "Create a plant care app",
    "Build a local services directory",
    "Develop a food delivery app",
    "Make a meditation app",
    "Design an online learning platform",
    "Create a digital resume builder",
    "Build a travel itinerary planner",
    "Develop an online marketplace",
    "Make a book library management system",
    "Design a gaming community website",
    "Create a recipe sharing app",
    "Build a charity donation platform",
    "Develop a restaurant reservation system",
    "Make a fashion blog",
    "Design an online voting system",
    "Create a virtual pet game",
    "Build a family tree maker",
    "Develop a smart home control app",
    "Make an online quiz generator",
    "Design a digital scrapbook",
    "Create a daily journal app",
    "Build a wedding planner website",
    "Develop a home workout app",
    "Make a neighborhood social network",
    "Design a meme generator",
    "Create an art portfolio website",
    "Build a custom calendar app",
    "Develop a chat application",
    "Make a price comparison website",
    "Design an audiobook app",
    "Create a resume analyzer",
    "Build a music playlist manager",
    "Develop a virtual classroom",
    "Make a sports score tracker",
    "Design a calorie counter app",
    "Create a gardening guide",
    "Build a volunteer coordination app",
    "Develop an inventory management system",
    "Make a baby name generator",
    "Design a cryptocurrency tracker",
    "Create a pet adoption website",
    "Build a recipe meal planner",
    "Develop a sales tracking system",
    "Make a cooking timer app",
    "Design an online bookstore",
    "Create a music notation app",
    "Build a school management system",
    "Develop an event ticketing system",
    "Make a food recipe app",
    "Design an energy consumption tracker",
    "Create a video editing tool",
    "Build a VR tour of a museum",
    "Develop a community forum",
    "Make a digital whiteboard",
    "Design a hiking trail finder",
    "Create a budget tracker",
    "Build a language translator app",
    "Develop a personal health record",
    "Make a custom greeting card maker",
    "Design a car maintenance tracker",
    "Create a virtual study group app",
    "Build a stock portfolio tracker",
    "Develop a digital clock app",
    "Make a habit tracker",
    "Design a personalized news feed",
    "Create a skill sharing platform",
    "Build a virtual reality game",
    "Develop an email newsletter generator",
    "Make a fashion design tool",
    "Design a book club organizer",
    "Create an inventory checklist app",
    "Build a discount alert app",
    "Develop a board game platform",
    "Make a historical timeline app",
    "Design a freelancer job board",
    "Create a project management tool",
    "Build a virtual garden planner",
    "Develop a smart grocery list",
    "Make an online auction site",
    "Design a music instrument tuner",
    "Create a therapy session scheduler",
    "Build a festival guide app",
    "Develop a local event finder",
    "Make a virtual workout buddy",
    "Design a cloud storage manager",
    "Create a study planner",
    "Build a digital photo frame",
    "Develop a workout routine generator",
    "Make a vacation planner",
    "Design a mobile payment app",
    "Create a restaurant menu app",
    "Build a weather forecast app",
    "Develop a carpooling app",
    "Make a real-time chat app",
    "Design a productivity timer",
    "Create a running tracker",
    "Build a virtual conference app",
    "Develop a personal shopping assistant",
    "Make a podcast creation tool",
    "Design a gift suggestion app",
    "Create a virtual wardrobe",
    "Build a financial goal tracker",
    "Develop a time zone converter",
    "Make a photo editing app",
    "Design a virtual scrapbook",
    "Create a video sharing platform",
    "Build a language learning game",
    "Develop a city guide app",
    "Make a diet planner",
    "Design a sleep tracker",
    "Create a VR travel experience",
    "Build a rental property manager",
    "Develop a stock market simulator",
    "Make a virtual museum tour",
    "Design a mental health tracker",
    "Create a food allergy tracker",
    "Build a podcast directory",
    "Develop a QR code generator",
    "Make a habit forming app",
    "Design a blockchain explorer",
    "Create a virtual book club",
    "Build a recipe ingredient calculator",
    "Develop a customer feedback app",
    "Make a travel budget planner",
    "Design a digital art gallery",
    "Create a multi-currency wallet",
    "Build a custom map generator",
    "Develop a festival organizer",
    "Make a digital attendance system",
    "Design a workout plan creator",
    "Create a study flashcards app",
    "Build a mental health journal",
    "Develop a sustainable living guide",
    "Make an eco-friendly product finder",
    "Design a bird watching app",
    "Create a plant identifier",
    "Build a VR real estate tour",
    "Develop a recipe substitution guide",
    "Make a personal diary app",
    "Design a virtual gift exchange",
    "Create a gaming news aggregator",
    "Build a music collaboration platform",
    "Develop a language pronunciation guide",
    "Make a charity event manager",
    "Design a virtual art exhibition",
    "Create a meal prep planner",
    "Build a virtual treasure hunt",
    "Develop a movie ticket booking app",
    "Make a smart recipe organizer",
    "Design a personalized horoscope app",
    "Create a mood tracker",
    "Build a book swapping platform",
    "Develop a virtual fitness coach",
    "Make a property valuation tool",
    "Design a recipe video app",
    "Create a virtual interview prep app",
    "Build a recipe cost calculator",
    "Develop a digital skill tracker",
    "Make an outdoor activity guide",
    "Design a virtual pen pal platform",
    "Create a workout challenge app",
    "Build a music mixing tool",
    "Develop a book recommendation engine",
    "Make a recipe nutritional calculator",
    "Design a daily habit tracker",
    "Create a virtual escape room",
    "Build a personal budgeting app",
    "Develop a healthy eating guide",
    "Make a podcast recommendation app",
    "Design a VR learning experience",
    "Create a motivational quote app",
    "Build a custom emoji creator",
    "Develop a photo journal app",
    "Make a product review aggregator",
    "Design a digital mood board",
    "Create a fitness progress tracker",
    "Build a virtual reality tour",
    "Develop a recipe collection app",
    "Make a language exchange platform",
    "Design a personal goal setting app",
    "Create a healthy recipe app",
    "Build a virtual reality meditation",
    "Develop a time management app",
    "Make a local business finder",
    "Design a recipe shopping list app",
    "Create a wellness journal",
    "Build a VR workout experience",
    "Develop a travel recommendation app",
    "Make a digital art creation tool",
    "Design a virtual cooking class",
    "Create a study aid app",
    "Build a personalized recipe app",
    "Develop a home organization app",
    "Make a workout tracker",
    "Design a virtual museum app",
    "Create a goal tracking app",
    "Build a VR relaxation app",
    "Develop a personal training app",
    "Make a healthy living guide",
    "Design a recipe rating app",
    "Create a personal finance guide",
    "Build a VR language learning app",
    "Develop a digital reading list",
    "Make a mental wellness guide",
    "Design a custom recipe app",
    "Create a travel journal",
    "Build a VR tour guide",
    "Develop a recipe box organizer",
    "Make a study timer app",
    "Design a workout plan app",
    "Create a digital planner",
    "Build a virtual reality museum",
    "Develop a personal development app",
    "Make a recipe planner",
    "Design a digital recipe book",
    "Create a VR travel planner",
    "Build a personal growth tracker",
    "Develop a digital habit tracker",
    "Make a workout routine app",
    "Design a virtual pet care app",
    "Create a daily planner",
    "Build a VR nature experience",
    "Develop a recipe organizer",
    "Make a home workout guide",
    "Design a virtual reality experience",
    "Create a personalized meal planner",
    "Build a digital habit journal",
    "Develop a workout log app",
    "Make a personal wellness app",
    "Design a VR fitness app",
    "Create a meal planning app",
];

// Function to get a random project idea
function getProjectIdea() {
    const randomIndex = Math.floor(Math.random() * projectIdeas.length);
    return projectIdeas[randomIndex];
}

// Event listener for the button
document.getElementById("ideaButton").addEventListener("click", function() {
    const idea = getProjectIdea();
    // Display the idea to the user
    // This could be a pop-up, an update to the DOM, an email, etc.
    alert(idea);
});